model_config:
  model_type: tiger

  input_channels: 2
  num_classes: 4

  tiger_config:
    n_srcs: 2
    n_fft: 256
    hop_length: 64
    win_length: 256
    center: true
    normalize_input: true
    eps: 1.0e-8
    # TIGER-specific architecture params
    out_channels: 128
    in_channels: 512
    num_blocks: 16
    upsampling_depth: 4
    att_n_head: 4
    att_hid_chan: 4
    nband: 8
