model_config:
  model_type: resunet1d_bottleneck_dccb_lssg

  input_channels: 2
  num_classes: 4
  n_stages: 5
  features_per_stage: [32, 64, 128, 256, 320]
  kernel_sizes: [3, 3, 3, 3, 3]
  strides: [1, 2, 2, 2, 2]
  n_conv_per_stage: [2, 2, 2, 2, 2]
  n_conv_per_stage_decoder: [2, 2, 2, 2]
  deep_supervision: false
  use_complex_mask: false

  # Bottleneck configuration
  bottleneck_mode: "dccb"
  
  # Skip configuration
  skip_mode: "lssg_channel"
