model_config:
  model_type: conformer_gridnet

  input_channels: 2
  num_classes: 4

  conformer_gridnet_config:
    n_srcs: 2
    n_fft: 256
    hop_length: 64
    win_length: 256
    center: true
    normalize_input: true
    eps: 1.0e-8
    # 架构参数
    n_layers: 3
    hidden_channels: 128
    attn_n_head: 4
    attn_qk_output_channel: 4
    emb_dim: 48
    emb_ks: 4
    emb_hs: 1
    # Conformer 参数
    conformer_n_head: 4
    conv_kernel_size: 31
    ff_expansion_factor: 2
    dropout: 0.1
